export const listingTableData = [
  {
    id: "b1a1e1a0-50d2-4d8e-a9a6-f687d7b2e32b",
    image: "/assets/images/thumbnaillist/02.jpg",
    title: "Gorgeous Villa Bay View",
    location: "Avenue South Burlington, Los Angles",
    price: "$212,000",
    priceType: "Fixed Amount",
    addedDate: "10 Jan, 2019",
    views: 34,
    comments: 5,
    actions: [
      { type: "edit", link: "#" },
      { type: "delete", link: "#" },
    ],
  },
  {
    id: "d2c2e2b1-60e3-5d9f-b2b7-g798e8c3f43d",
    image: "/assets/images/thumbnaillist/02.jpg",
    title: "Gorgeous Villa Bay View",
    location: "Avenue South Burlington, Los Angles",
    price: "$212,000",
    priceType: "Fixed Amount",
    addedDate: "10 Jan, 2019",
    views: 34,
    comments: 5,
    actions: [
      { type: "edit", link: "#" },
      { type: "delete", link: "#" },
    ],
  },
  {
    id: "f3d3f3c2-71f4-6eaf-c3c8-h8a9e9d4f54e",
    image: "/assets/images/thumbnaillist/02.jpg",
    title: "Gorgeous Villa Bay View",
    location: "Avenue South Burlington, Los Angles",
    price: "$212,000",
    priceType: "Fixed Amount",
    addedDate: "10 Jan, 2019",
    views: 34,
    comments: 5,
    actions: [
      { type: "edit", link: "#" },
      { type: "delete", link: "#" },
    ],
  },
  {
    id: "g4e4g4d3-82g5-7fb0-d4d9-i9b0e0e5g65f",
    image: "/assets/images/thumbnaillist/02.jpg",
    title: "Gorgeous Villa Bay View",
    location: "Avenue South Burlington, Los Angles",
    price: "$212,000",
    priceType: "Fixed Amount",
    addedDate: "10 Jan, 2019",
    views: 34,
    comments: 5,
    actions: [
      { type: "edit", link: "#" },
      { type: "delete", link: "#" },
    ],
  },
  {
    id: "h5f5h5e4-93h6-8gc1-e5e0-j0c1f1f6h76g",
    image: "/assets/images/thumbnaillist/02.jpg",
    title: "Gorgeous Villa Bay View",
    location: "Avenue South Burlington, Los Angles",
    price: "$212,000",
    priceType: "Fixed Amount",
    addedDate: "10 Jan, 2019",
    views: 34,
    comments: 5,
    actions: [
      { type: "edit", link: "#" },
      { type: "delete", link: "#" },
    ],
  },
  {
    id: "i6g6i6f5-a4i7-9hd2-f6f1-k1d2g2g7i87h",
    image: "/assets/images/thumbnaillist/02.jpg",
    title: "Gorgeous Villa Bay View",
    location: "Avenue South Burlington, Los Angles",
    price: "$212,000",
    priceType: "Fixed Amount",
    addedDate: "10 Jan, 2019",
    views: 34,
    comments: 5,
    actions: [
      { type: "edit", link: "#" },
      { type: "delete", link: "#" },
    ],
  },
  {
    id: "j7h7j7g6-b5j8-aje3-g7g2-l2e3h3h8j98i",
    image: "/assets/images/thumbnaillist/02.jpg",
    title: "Gorgeous Villa Bay View",
    location: "Avenue South Burlington, Los Angles",
    price: "$212,000",
    priceType: "Fixed Amount",
    addedDate: "10 Jan, 2019",
    views: 34,
    comments: 5,
    actions: [
      { type: "edit", link: "#" },
      { type: "delete", link: "#" },
    ],
  },
  {
    id: "k8i8k8h7-c6k9-bkf4-h8h3-m3f4i4i9k09j",
    image: "/assets/images/thumbnaillist/02.jpg",
    title: "Gorgeous Villa Bay View",
    location: "Avenue South Burlington, Los Angles",
    price: "$212,000",
    priceType: "Fixed Amount",
    addedDate: "10 Jan, 2019",
    views: 34,
    comments: 5,
    actions: [
      { type: "edit", link: "#" },
      { type: "delete", link: "#" },
    ],
  },
  {
    id: "l9j9l9i8-d7la-clg5-i9i4-n4g5j5j0l10k",
    image: "/assets/images/thumbnaillist/02.jpg",
    title: "Gorgeous Villa Bay View",
    location: "Avenue South Burlington, Los Angles",
    price: "$212,000",
    priceType: "Fixed Amount",
    addedDate: "10 Jan, 2019",
    views: 34,
    comments: 5,
    actions: [
      { type: "edit", link: "#" },
      { type: "delete", link: "#" },
    ],
  },
];
